"""
shortcut.py — Create a platform-specific launcher for the QuickShare OBS profile.

macOS:   ~/Applications/OBS QuickShare.command  (executable shell script)
Windows: ~/Desktop/OBS QuickShare.lnk            (Windows shell link)
Linux:   ~/.local/share/applications/obs-quickshare.desktop
"""

from __future__ import annotations

import platform
import shutil
import stat
import sys
from pathlib import Path

PROFILE_NAME    = "QuickShare"
COLLECTION_NAME = "QuickShare"
SHORTCUT_LABEL  = "OBS QuickShare"

# OBS binary locations per platform
_OBS_BINARY: dict[str, list[Path]] = {
    "Darwin": [
        Path("/Applications/OBS.app/Contents/MacOS/OBS"),
        Path("/Applications/OBS.app/Contents/MacOS/obs"),
    ],
    "Windows": [
        Path(r"C:\Program Files\obs-studio\bin\64bit\obs64.exe"),
        Path(r"C:\Program Files (x86)\obs-studio\bin\64bit\obs64.exe"),
    ],
    "Linux": [
        Path("/usr/bin/obs"),
        Path("/usr/local/bin/obs"),
        Path("/snap/bin/obs-studio"),
        Path("/var/lib/flatpak/exports/bin/com.obsproject.Studio"),
    ],
}

OBS_FLAGS = [
    "--profile", PROFILE_NAME,
    "--collection", COLLECTION_NAME,
    # "--minimize-to-tray" intentionally omitted:
    # When OBS is hidden to the system tray, its AutoRemux dialog cannot
    # render (it is a child of the hidden main window), so RemuxAfterRecord
    # silently aborts and no MP4 is produced.  Keeping OBS visible also lets
    # users see the recording state and the remux progress bar.
    # A proper tray/menu-bar app is tracked in GitHub Issue #1 (.app bundle).
    "--startrecording",
]


def find_obs_binary(system: str | None = None) -> Path | None:
    """Return the first OBS binary path that exists, or None."""
    s = system or platform.system()
    for candidate in _OBS_BINARY.get(s, []):
        if candidate.exists():
            return candidate
    return None


# ---------------------------------------------------------------------------
# macOS: .command file
# ---------------------------------------------------------------------------

def _macos_shortcut_path() -> Path:
    # ~/Applications is user-writable; preferred over ~/Desktop for app launchers
    apps_dir = Path.home() / "Applications"
    apps_dir.mkdir(exist_ok=True)
    return apps_dir / f"{SHORTCUT_LABEL}.command"


def _find_obs_quickshare_bin() -> Path | None:
    """
    Locate the obs-quickshare executable for embedding in the launcher script.

    Search order:
      1. Same bin/ directory as the running Python interpreter (venv, pipx,
         developer editable install).
      2. macOS user pip install location: ~/Library/Python/<ver>/bin/
         (used when installed with `pip install --user` or system Python).
      3. PATH fallback.
    """
    # 1. Co-located with the Python that is running us right now.
    candidate = Path(sys.executable).parent / "obs-quickshare"
    if candidate.exists():
        return candidate

    # 2. macOS `pip install --user` drops scripts here.
    if platform.system() == "Darwin":
        import glob as _glob
        pattern = str(Path.home() / "Library" / "Python" / "*" / "bin" / "obs-quickshare")
        matches = sorted(_glob.glob(pattern))  # sorted → highest version last
        if matches:
            return Path(matches[-1])

    # 3. Anything on PATH.
    found = shutil.which("obs-quickshare")
    return Path(found) if found else None


def _write_macos_shortcut(obs_binary: Path | None, force: bool) -> Path:
    dest = _macos_shortcut_path()

    if dest.exists() and not force:
        raise FileExistsError(
            f"Shortcut already exists at {dest}. Use --force to overwrite."
        )

    # Use `open -W -a OBS` rather than exec'ing the binary directly.
    # -W      : wait for the app to quit before the shell script exits, so
    #           the Terminal window stays open while OBS is running and the
    #           user can see watcher output after they stop recording.
    # open -a : routes through Launch Services, so macOS TCC correctly
    #           attributes screen-recording / camera / mic permissions to
    #           OBS.app (bundle ID com.obsproject.obs-studio) rather than
    #           to this shell process.
    flags_str  = " ".join(f'"{f}"' for f in OBS_FLAGS)
    obs_qs_bin = _find_obs_quickshare_bin()
    watcher_line = (
        f'"{obs_qs_bin}" watch &'
        if obs_qs_bin
        else "# obs-quickshare not found on PATH — skipping watcher"
    )

    script = f"""\
#!/usr/bin/env bash
# OBS QuickShare launcher — generated by obs-quickshare
# Opens OBS with the QuickShare profile and starts recording immediately.

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  OBS QuickShare"
echo "  Recording starts automatically in OBS."
echo "  When done: click Stop Recording in OBS, then"
echo "  quit OBS (Cmd+Q) to save and export your file."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Start the file watcher so it is ready the moment OBS finishes remuxing.
{watcher_line}
WATCHER_PID=$!

# -W keeps this script alive until OBS quits, so the Terminal window shows
# watcher output. Open goes via Launch Services → correct TCC attribution.
open -W -a OBS --args {flags_str}

echo ""
echo "  OBS quit. Waiting for recording to finish processing…"
echo "  (You will see a 'Moved:' line when your file is ready.)"
echo ""

# Give the watcher up to 60 s to detect, stabilise, and move the final file.
# The stability check itself takes ~15 s minimum; 60 s is a safe ceiling.
sleep 60
kill "$WATCHER_PID" 2>/dev/null
wait "$WATCHER_PID" 2>/dev/null
echo "  Done. You can close this window."
"""
    dest.write_text(script, encoding="utf-8")

    # Make executable
    current_mode = dest.stat().st_mode
    dest.chmod(current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    return dest


# ---------------------------------------------------------------------------
# Windows: .lnk via pywin32 (optional dep) or fallback .bat file
# ---------------------------------------------------------------------------

def _windows_shortcut_path(use_lnk: bool) -> Path:
    desktop = Path.home() / "Desktop"
    if not desktop.exists():
        # OneDrive-backed desktop
        desktop = Path.home() / "OneDrive" / "Desktop"
    ext = ".lnk" if use_lnk else ".bat"
    return desktop / f"{SHORTCUT_LABEL}{ext}"


def _write_windows_lnk(obs_binary: Path, dest: Path) -> None:
    """Create a .lnk shortcut using pywin32 (win32com)."""
    import win32com.client  # type: ignore[import]

    shell = win32com.client.Dispatch("WScript.Shell")
    shortcut = shell.CreateShortCut(str(dest))
    shortcut.TargetPath = str(obs_binary)
    shortcut.Arguments  = " ".join(OBS_FLAGS)
    shortcut.WorkingDirectory = str(obs_binary.parent)
    shortcut.IconLocation = str(obs_binary)
    shortcut.Description = "Start OBS with QuickShare profile"
    shortcut.Save()


def _write_windows_bat(obs_binary: Path | None, dest: Path) -> None:
    """Fallback: write a .bat file if pywin32 is not available."""
    obs_path = obs_binary or Path(r"C:\Program Files\obs-studio\bin\64bit\obs64.exe")
    flags_str = " ".join(OBS_FLAGS)
    bat = f'@echo off\nstart "" "{obs_path}" {flags_str}\n'
    dest.write_text(bat, encoding="utf-8")


def _write_windows_shortcut(obs_binary: Path | None, force: bool) -> Path:
    try:
        import win32com.client  # noqa: F401
        has_win32com = True
    except ImportError:
        has_win32com = False

    dest = _windows_shortcut_path(use_lnk=has_win32com)

    if dest.exists() and not force:
        raise FileExistsError(
            f"Shortcut already exists at {dest}. Use --force to overwrite."
        )

    if has_win32com and obs_binary:
        _write_windows_lnk(obs_binary, dest)
    else:
        _write_windows_bat(obs_binary, dest)

    return dest


# ---------------------------------------------------------------------------
# Linux: .desktop file
# ---------------------------------------------------------------------------

def _linux_shortcut_path() -> Path:
    apps_dir = Path.home() / ".local" / "share" / "applications"
    apps_dir.mkdir(parents=True, exist_ok=True)
    return apps_dir / "obs-quickshare.desktop"


def _write_linux_shortcut(obs_binary: Path | None, force: bool) -> Path:
    dest = _linux_shortcut_path()

    if dest.exists() and not force:
        raise FileExistsError(
            f"Shortcut already exists at {dest}. Use --force to overwrite."
        )

    obs_path = obs_binary or Path("/usr/bin/obs")
    flags_str = " ".join(OBS_FLAGS)

    desktop_entry = f"""\
[Desktop Entry]
Version=1.0
Type=Application
Name={SHORTCUT_LABEL}
Comment=Start OBS with QuickShare profile and begin recording
Exec={obs_path} {flags_str}
Icon=obs
Terminal=false
Categories=AudioVideo;Video;Recorder;
StartupNotify=false
"""
    dest.write_text(desktop_entry, encoding="utf-8")
    current_mode = dest.stat().st_mode
    dest.chmod(current_mode | stat.S_IXUSR)

    return dest


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def shortcut_exists() -> bool:
    system = platform.system()
    if system == "Darwin":
        return _macos_shortcut_path().exists()
    elif system == "Windows":
        return _windows_shortcut_path(use_lnk=True).exists() or \
               _windows_shortcut_path(use_lnk=False).exists()
    else:
        return _linux_shortcut_path().exists()


def write_shortcut(force: bool = False) -> Path:
    """
    Create the OBS QuickShare launcher for the current platform.

    Returns the path of the created file.
    Raises FileExistsError if shortcut exists and force=False.
    Raises RuntimeError if OBS binary cannot be located (warning only — shortcut
    is written with a best-guess path so the user can fix it manually).
    """
    system = platform.system()
    obs_binary = find_obs_binary(system)

    if obs_binary is None:
        # Don't abort — write the shortcut with the default path and warn
        print(
            "Warning: OBS binary not found in standard locations. "
            "The shortcut will use a default path — edit it if OBS is installed elsewhere.",
            file=sys.stderr,
        )

    if system == "Darwin":
        return _write_macos_shortcut(obs_binary, force=force)
    elif system == "Windows":
        return _write_windows_shortcut(obs_binary, force=force)
    else:
        return _write_linux_shortcut(obs_binary, force=force)
